#!/usr/lpp/IBM/cnj/IBM/node-latest-os390-s390x/bin/node
/*
 * Sample Node.js program demonstrating SIGTERM handler for operator STOP (P) command.
 * Includes SIGINT handler for Ctrl-C break when run interactively.
 */

const everyOneMinute = (60 * 1000)

const timer = setInterval( () => {
  console.log(new Date())
},everyOneMinute)

const cleanup = (signal) => {
  console.error(`signal: ${signal}`)
  clearInterval( timer )
}

process.on('SIGTERM', (signal) => { cleanup(signal) })
process.on('SIGINT', (signal) => { cleanup(signal) })

console.log("Running")
